version = 0.1

[default]
[default.global.parameters]
stack_name = "CodeSensei-backend"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
region = "us-east-1"
parameter_overrides = "Environment=prod CorsAllowedOrigin=https://main.dnq80x6al42k7.amplifyapp.com"

[default.validate.parameters]
lint = true

[default.sync.parameters]
watch = true

[dev]
[dev.global.parameters]
stack_name = "codesensei-backend-dev"

[dev.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
region = "us-east-1"
parameter_overrides = "Environment=dev CorsAllowedOrigin=https://main.dnq80x6al42k7.amplifyapp.com"

